# Generated by Django 3.2.1 on 2021-10-29 19:28

from django.db import migrations, models
import newsletters.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'NewsLetter Messages',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', newsletters.fields.LowerEmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
